CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    document VARCHAR(14) NOT NULL UNIQUE,
    email VARCHAR(254) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    type VARCHAR(10) NOT NULL CHECK (type IN ('COMMON', 'MERCHANT')),
    balance NUMERIC(19, 2) NOT NULL DEFAULT 0 CHECK (balance >= 0),
    CHECK (document ~ '^([0-9]{11}|[0-9]{14})$'),
    CHECK (email = lower(email))
);

CREATE TABLE transfers (
    id UUID PRIMARY KEY,
    payer_id BIGINT NOT NULL REFERENCES users(id),
    payee_id BIGINT NOT NULL REFERENCES users(id),
    amount NUMERIC(19, 2) NOT NULL CHECK (amount > 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    notified_at TIMESTAMP WITH TIME ZONE,
    next_notification_at TIMESTAMP WITH TIME ZONE NOT NULL,
    notification_attempts INTEGER NOT NULL DEFAULT 0,
    CHECK (payer_id <> payee_id)
);

CREATE INDEX idx_transfers_pending_notification
    ON transfers(next_notification_at) WHERE notified_at IS NULL;
