server {
    listen 80;
    access_log off;

    location = /authorize {
        default_type application/json;
        return 200 '{"status":"success","data":{"authorization":true}}';
    }

    location = /notify {
        return 204;
    }
}
